### ISSUE TITLE
Support english phrasal verbs

### ISSUE THREAD

**Issue by Nitrino** [Nitrino/easysubs#121]
Detect idioms in the text and display their meaning

**Comment by Nitrino** [comment]
Dictionaries:
https://github.com/quinnjn/idioms.js/blob/master/idioms.js
[large_list_of_english_idioms_from_a_to_z.pdf](https://github.com/Nitrino/easysubs/files/4057908/large_list_of_english_idioms_from_a_to_z.pdf)
[idiomsatozpdf.pdf](https://github.com/Nitrino/easysubs/files/4057909/idiomsatozpdf.pdf)

**Comment by Ilya-Lad** [comment]
It would be a very interesting initiative. Very needed just in movies. Full support.

**Comment by Nitrino** [comment]
List of phrasal verbs 
https://www.skypeenglishclasses.com/english-phrasal-verbs/
