### ISSUE TITLE
Проблема с установкой плагина в браузер.

### ISSUE THREAD

**Issue by LeWombat** [Nitrino/easysubs#123]
### При совершении действий по инструкции, а именно на пункте распаковки плагина в браузер, происходит ошибка: "

> Не удалось загрузить страницу параметров index.html.
> Не удалось загрузить манифест.

"
При загрузке прошлых версий, все работает отлично

**Comment by Nitrino** [comment]
@LeWombat 
Кажется при установке вы выбираете корневой каталог. Нужно выбрать папку `dist`.

**Comment by Nitrino** [comment]
@LeWombat Теперь расширение доступно в официальном магазине Chrome.
https://chrome.google.com/webstore/detail/easysubs/ocelmccppkcibiflhhepafdjjomimddf
