### ISSUE TITLE
Translating from languages with special characters

### ISSUE THREAD

**Issue by anagilda** [Nitrino/easysubs#131]
Hey!

I really like the idea of this extension, I believe it can be very helpful for me. However, it does not work for translating from the language I want to learn – Russian.

I would really appreciate help in making it work.

Thanks in advance!

### Description of the problem

When trying to use this extension to get a translation of a **single word** by hovering it, it does not work for my case (Russian to English).

However, translating the full subtitle by clicking works as expected for the same translation pair (Russian to English).

### Reproducing the problem

1. Set _translation language_ to _English_.
2. Watch any video in a language with subtitles with special characters like Russian (all letters) or Portuguese (letters like ã, é, etc...)
3. Hover over a word with those characters.

### Observed results

Cut off words being translated, ending before special characters like accented letters, or no pop-up at all in case of words with a different alphabet.

Example from Portuguese to English (taken from [here](https://www.youtube.com/watch?v=ApBGWJNE6t4)):

![](https://i.gyazo.com/5789c5155ac85f84d7ab7add7179d32f.png)

Example from Russian to English (taken from [here](https://www.youtube.com/watch?v=_ufeBvcGKf8))

![](https://gyazo.com/72736e64de69e8c0c40e375cfbde8eb5.png)

### Expected results

Translation for the full hovered word, as seen [in the documentation](https://github.com/Nitrino/easysubs#word-and-full-subtitle-translation).

**Comment by Nitrino** [comment]
Hey @anagilda.
Thank you for your wonderful detailed report.
These are two different bugs, I will fix them soon.

**Comment by Nitrino** [comment]
@anagilda Fixed in master. 
Unfortunately, the official release will be only in a couple of weeks, since Google has a very long review. 
If you want to participate in beta testing, you can send me an email. 
Or you can install the dev version according to the [instructions.](https://github.com/Nitrino/easysubs#install-dev-version)

I will be glad to any feedback

**Comment by anagilda** [comment]
@Nitrino I installed the dev version and it works perfectly. 

Thank you so much!

**Comment by Nitrino** [comment]
@anagilda New version available in Chrome Store
https://chrome.google.com/webstore/detail/easysubs/ocelmccppkcibiflhhepafdjjomimddf?hl=ru

**Comment by anagilda** [comment]
@Nitrino Thank you so much for letting me know!
