### ISSUE TITLE
Long subtitles overflow

### ISSUE THREAD

**Issue by xamgore** [Nitrino/easysubs#152]
Hi! Thank you for such a great extension!

There are still some issues connected with the `white-space: pre` rule set on the subtitles box:

![image](https://user-images.githubusercontent.com/4586392/81935258-03b7e480-95f9-11ea-8ff7-8e54e092808d.png)

[Video, 15s](https://www.youtube.com/watch?v=PFNdIup9kS0). I believe `white-space: pre-line` is preferred with constraints on the box width.

**Comment by Nitrino** [comment]
Hi @xamgore. Thanks for the report. 
I will fix this bug soon!
