### ISSUE TITLE
Netflix sometimes can't load subtitles

### ISSUE THREAD

**Issue by sinCereXuYuan** [Nitrino/easysubs#153]
Thanks for this awesome extension. But I have a annoying issue that the extension sometimes work sometimes don't. 

After some debug, I found that when it's ipv6 subtitle url, it worked, when it's ipv4 subtitle url, chrome complains ERR_SSL_VERSION_OR_CIPHER_MISMATCH. 

I'm using ExpressVPN, don't know if it's an issue. 

Can I somehow force the extension to load ipv6 subtitle url ?

**Comment by Nitrino** [comment]
Hi @sinCereXuYuan, thanks for the feedback!
Some clarifying questions:
1. Which browser and operating system are you using?
2. Does this occur on certain videos or randomly? can I repeat it somehow?

This problem seems to apply to your browser. 
Have you tried ways to solve this problem? eg:
https://medium.com/@thesslstore/err-ssl-version-or-cipher-mismatch-fix-it-within-5-minutes-e7758cf3bc44
https://www.hostinger.com/tutorials/ssl-version-cipher-mismatch-error

**Comment by sinCereXuYuan** [comment]
Hi Nitrino
Thanks for your help! 

1. I have tried firefox/chrome both in windows and macos, also safari in macos. All failed.
2. It seems netflix randomly choose ipv4/ipv6 subtitles. When it's ipv6 subtitle url, the video is OK, when it's ipv4 subtitle url, the video failed. (But I can refresh several times, and sometimes it will choose ipv6 subtitle url and succeds)
3. Now I am certain it's also VPN issue. After close expressVPN, I can manually download ipv4 subtitle url and load it in the extension. 
4. I also contacted expressVPN team, with no luck.
5. I think my best option would be try to add iptable rules so that subtitle use direct link .. 


6. It seems new version of chrome doesn't have this ssl setting anymore. But I tried it on firefox with no luck.
<img width="1438" alt="Screen Shot 2020-05-16 at 11 55 00 AM" src="https://user-images.githubusercontent.com/42259790/82109989-7e097580-976d-11ea-8f29-af01b2b18707.png">
<img width="975" alt="Screen Shot 2020-05-16 at 12 05 33 PM" src="https://user-images.githubusercontent.com/42259790/82109998-91b4dc00-976d-11ea-8b78-3e20ad5ef3eb.png">
 

Example url:
https://ipv4-c076-lhr004-ix.1.oca.nflxvideo.net/?o=AQMbdeTNLxzMcp9UNGMyIU2CfCNdjOx22pss0nz4Qqh9dguvfVV_pZCUA0Z_TRRgThTGsbFd-D1izKsBeaGospmFt3sQ9SnbFNIaD0FhuWKiS6-cUDC1RaEPg7Mh-bGaOqdLY_CUE4IwjeyctwjhiU9Ci_-KlCwKi0iy0VXuRirnixSZZ-RbkvwlV3o&v=5&e=1589586212&t=iZk4qKBV1HWFHwiE6IBR5EG7_94

**Comment by sinCereXuYuan** [comment]
Hi Nitrino

After change function `this.randomProperty ` to choose ipv6 url, the extension worked well for me. 

Thanks for the very helpful extension again!

**Comment by Nitrino** [comment]
@sinCereXuYuan Thanks fo research. 
Are you planning to make a pull request with a fix?

**Comment by sinCereXuYuan** [comment]
Hi
I haven't pushed any commit to public github repository before, and when I push, it told me `Please make sure you have the correct access rights and the repository exists.`

It's pretty simple, so I just paste my change here. 

>  this.randomProperty = function (obj) {
        var keys = Object.keys(obj); // tslint:disable-next-line: no-bitwise
        var index, value;
        for (index = 0; index < keys.length; ++index) {
            value = obj[keys[index]];
            if (value.substring(0, 12) === "https://ipv6") { // ipv4 may cause ERR_SSL_VERSION_OR_CIPHER_MISMATCH when VPN connected
                return value;
            }
        }
    };

Also, there is a feature suggestion. On click the word, open a new tab to search google definition. 
(or UI let user input url, and concatenate the clicked word to the url and open in a new tab. This way, you can have a lot of dictionaries at disposal .. ) Such as, `https://www.google.com/search?q=define+test`

**Comment by Nitrino** [comment]
@sinCereXuYuan Ok, I'll fix it myself. 
По поводу предложения: Can you explain what flow use of this?

**Comment by sinCereXuYuan** [comment]
Hi Nitrino:

I changed code like this personally. ( English-to-English dictionary fit my use much more. But it doesn't match with extension user interface.. )

The url here ` var url = "https://www.google.com/search?q=define+"+message.value;` could let user customize, such as `var url = "www.etymonline.com/search?q="+message.value;`, so that more user can benefit from it. 

![image](https://user-images.githubusercontent.com/42259790/82543427-1a74b300-9b86-11ea-98af-e5160589008d.png)
![image](https://user-images.githubusercontent.com/42259790/82543480-2fe9dd00-9b86-11ea-87a9-84cd4f67ada1.png)

**Comment by Nitrino** [comment]
Hi @sinCereXuYuan 
I just have plans to support various translation sources. 
I note that you are editing javascript files from the `dist` folder, it is better to edit typescript sources from the`src` folder and compile. https://github.com/Nitrino/easysubs/blob/master/src/background.ts#L6

**Comment by sinCereXuYuan** [comment]
Hi Nitrino

Thanks for the advice!

**Comment by sinCereXuYuan** [comment]
Hi Nitrino

I recently switched from ExpressVPN to bandwagon VPS, turns out subcache only has ipv4 address now(and no security problem like before), and by filter ipv6 address, actually creates problem. 

Sorry for the trouble.

**Comment by Nitrino** [comment]
Hi @sinCereXuYuan 
I'm glad that your problem was solved
