### ISSUE TITLE
helloo where is the updates? 

### ISSUE THREAD

**Issue by hichemqq** [Nitrino/easysubs#158]
hi nitrino, it seems that you added a lot of updates like anki support for example but how can i get that updates? i don't know when i click update extension in chrome it says everything is updated but i don"t get your enhancements thanks

**Comment by Nitrino** [comment]
Hi @hichemqq 
Open issues are tasks and discussions for implementation. After implementation or rejection, they close. 
Anki support is in the plans, but not yet implemented.

You can install the dev version without waiting for the release in the store, but then you will have to update it manually. https://github.com/Nitrino/easysubs#install-dev-version
