### ISSUE TITLE
Subtiteles color

### ISSUE THREAD

**Issue by womchik** [Nitrino/easysubs#173]
Hi!

Can you add color selection?
Sometimes subtitles intersect with captions and are poorly visible.

**Comment by hatarist** [comment]
Also, a way to change the background opacity. Usually it's opaque black background, but EasySubs currently implements either transparent background or a 50% opaque one.

**Comment by Nitrino** [comment]
@womchik @hatarist Hi guys.
Can you send examples of videos on which subtitles are hard to see?
I try not to overload the plugin with settings and want to think about how to improve the display of subtitles

**Comment by womchik** [comment]
<img width="1532" alt="image" src="https://user-images.githubusercontent.com/322341/94642255-4b12e900-02ec-11eb-80ca-e6e3578c59b2.png">
