### ISSUE TITLE
No Google translate token when using extension behind VPN

### ISSUE THREAD

**Issue by troggy** [Nitrino/easysubs#191]
When I move the mouse over the word, playback stops and the word is highlighted, but no word translation anymore.
It worked at first after the installation, but very soon stopped appearing. Full sentence popup still works. 

I've quickly picked into debugger and found out that `isUnmounted.current` is being [set](https://github.com/Nitrino/easysubs/blob/master/src/components/subs/TranslateWordPopup.tsx#L49) before the response for `getSingleTranslation` comes. Thus when the response comes it is being [ignored](https://github.com/Nitrino/easysubs/blob/master/src/components/subs/TranslateWordPopup.tsx#L35)

Reproduced on two different machines (MacOS + Firefox and MacOS + Chrome). Both run on the same network, so, perhaps, it could be related to the network.

**Comment by troggy** [comment]
My best guess: google translate denies the request (both machines are using VPN and I usually see a lot of captchas when using google services)

**Comment by Nitrino** [comment]
@troggy Hi. 
The error is related to the rate limit of google translate. 
Will be fixed in the next version.
