### ISSUE TITLE
Arrows rewind 

### ISSUE THREAD

**Issue by badbcentral** [Nitrino/easysubs#193]
In YouTube, when I press arrow keys - it's very annoying to rewind back (you gotta press arrow left key two times very quickly to switch to the previous subtitle, it's also hard when you want to substantially move backward/forward). Force rewind, that's mentioned in Readme - doesn't work, when I press alt with arrows my browser goes back and forward in page history. 
I'd really like to have a checkbox that turns off extension's rewind physic and brings it back to normal.

**Comment by Nitrino** [comment]
Hi @badbcentral 
What browser are you using?

**Comment by badbcentral** [comment]
@Nitrino 
Hey, Chrome

**Comment by hrdrq** [comment]
Same here with Netflix!
And pressing arrow left key two times very quickly thing doesn't work either😅
(Chrome on macOS)

**Comment by Nitrino** [comment]
@badbcentral @hrdrq Can't repeat, can you record a video of the bug?

**Comment by hrdrq** [comment]
Hi, in 1 to 5 seconds, I was pressing `←` several times,
and in 7 to 9 seconds, I was pressing `option + ←` several times.
https://user-images.githubusercontent.com/33222939/109300917-89500c80-787a-11eb-8254-dffe4ace0805.mov

**Comment by Nitrino** [comment]
@hrdrq Thanks, there seems to be a bug with overlapping subtitles. I will try to fix it in the coming days

**Comment by badbcentral** [comment]
@Nitrino hey, it still wasn't fixed :(

**Comment by badbcentral** [comment]
@Nitrino  я умоляю, прошу, почините :(((((( сделайте просто обычную нормальную перемотку(
это расширение одно из самых быстрых среди аналогов, но я все еще не могу им пользоваться
https://user-images.githubusercontent.com/67790845/128771343-b799f98c-6780-401d-830e-d45d0b3b6cd5.mp4

**Comment by Nitrino** [comment]
@badbcentral Привет. 
Я услышал твою боль и исправил перемотку субтитров с наложением, теперь должно работать как положено. 
Так же в настройках добавил возможность отключить перемотку по субтитрам. 

Мне нужно еще несколько дней привести проект в порядок в связи с обновлением библиотек и потом выпущу новый релиз. 
Пока протестируй плиз работу этой версии 
[release.zip](https://github.com/Nitrino/easysubs/files/6970562/release.zip)

**Comment by Nitrino** [comment]
I will leave the issue open until the release of the new version

**Comment by badbcentral** [comment]
@Nitrino 
работает
а вообще надо бы прикрутить какой-нибудь бесплатный сервис изучения слов, или же сделать встроенный словарь, как у расширение wordzzz https://chrome.google.com/webstore/detail/wordzzz-%E2%80%93-learn-language/iekapmfhbnlnpgapdilmdlehfmelengm

**Comment by Nitrino** [comment]
@badbcentral есть в планах больше интеграций + свой словарь
