### ISSUE TITLE
Doesn't work well on Netflix 

### ISSUE THREAD

**Issue by hrdrq** [Nitrino/easysubs#194]
Hi, thank you for developing this excellent extension.
But it's not doing well with Netflix.
First time I installed easysubs, it worked perfectly,
but now there is bug.
(I tried Chrome and Firefox on macOS Catalina.

The problem is that the subtitle is not showing.
The subtitle appears when I disable easysubs, like the video below.

I'm trying debugging it, but I'm not familiar with typescript :(
If you have any ideas, please let me know!
Thank you

https://user-images.githubusercontent.com/33222939/108827808-62d76a80-7609-11eb-8624-ba5296b3ed14.mov

**Comment by Nitrino** [comment]
Hi @hrdrq,
Thanks for the report. 
It seems Netflix made changes in the player, I will try to fix it in the next few days

**Comment by hrdrq** [comment]
Thanks a lot! In the source code, what part is causing the problem?

**Comment by Nitrino** [comment]
@hrdrq I have already fixed the work and released version 1.5.4. 
It is already available in the [firefox store](https://addons.mozilla.org/en-US/firefox/addon/easysubs/), it will appear in the chrome store after the review

**Comment by hrdrq** [comment]
Thank you for the quick fix!
