### ISSUE TITLE
Use it for file from computer

### ISSUE THREAD

**Issue by Shirobachi** [Nitrino/easysubs#196]
I would love to use your extention with Downloaded files, It would be very helpful <3

**Comment by Nitrino** [comment]
Hi @Shirobachi 
I have some experience in this, but unfortunately, this feature will not work with many videos, since the browser does not support them. For example, browsers do not support the common AC-3 codec

**Comment by Shirobachi** [comment]
Got it, Im using linux, maybe you know something what you can recommend me?

**Comment by Nitrino** [comment]
@Shirobachi Sorry, I can't recommend anything for local viewing
