### ISSUE TITLE
Horizontal scrollbar appears in the translation popup

### ISSUE THREAD

**Issue by jtraub** [Nitrino/easysubs#202]
Sometimes horizontal scrollbar appears in the translation popup. I believe this happens when vertical scrollbar is present in the popup.

While vertical space is a scarce resource on modern screens horizontal space is not so scarce so I think we should avoid horizontal scrollbar as it makes it harder to use the extension.

![image](https://user-images.githubusercontent.com/153191/118167459-0f3b2700-b46a-11eb-90d2-46fe855ad41b.png)

P.S. I can take a look into the problem over the weekend if you want

**Comment by jtraub** [comment]
@Nitrino hey, sorry I totally forgot to share [my fix](https://github.com/jtraub/easysubs/commit/798f1040b86a42ed09c48f8bfb553dd6f9eea676)

First of all, only Firefox is affected by this issue. It happens due to the fact that `::-webkit-scrollbar` pseudo-element is [not supported](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar#browser_compatibility) in the browser.

Basically scrollbar width in Firefox can be either `normal` or `thin` (see [scrollbar-width](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width) property supported only by Firefox) but even with these values actual width depends on platform and applied window manager theme. For example I am using Linux and thin scrollbar in my current theme has width of 4px but another theme that I sometimes switch to offers thin scrollbars with width of 7px, I think.

The idea behind the fix is to detect that the extension is running in Firefox (using technique described in https://stackoverflow.com/a/9851769/471899 because detection through user agent is not reliable) and then measure scrollbar width by inserting an empty div with a scrollbar into the DOM. After that I update `padding-right` on `#easysubs .easysubs-translate-alternative` to make sure it can take the scrollbar. CSS custom properties were used to accommodate design/element tree changes in the future releases.

Before applying the fix to 1.5.6
![image](https://user-images.githubusercontent.com/153191/149570321-5a47624e-d4b7-4f3f-ac60-ac651fbe5691.png)
After
![image](https://user-images.githubusercontent.com/153191/149570388-c445aa61-e821-4097-8531-2a9baba0b397.png)

**Comment by Nitrino** [comment]
@jtraub Hi. I'll try to fix it soon thanks for the investigation
If you have a desire to help, you can send a PR
