### ISSUE TITLE
Translation doesn't show up on YouTube

### ISSUE THREAD

**Issue by Sentero-esp12** [Nitrino/easysubs#204]
I've just installed the extension, it loads the interface and I can access Easysubs settings, but if I hover the words, they turn blue, but nothing happens besides that, and if I click a word, the word turns grey again, but also nothing else happens. 

FireFox 90.0

**Comment by Nitrino** [comment]
Hi @Sentero-esp12 
Perhaps your translation language is the same as the subtitle language. 
Check that the desired language is set in the settings
<img width="400" alt="image" src="https://user-images.githubusercontent.com/1032291/126159005-19dc5341-77ff-450b-8b16-19cd93109b3e.png">

**Comment by Sentero-esp12** [comment]
Hi @Nitrino, the subtitles are in a different language. The "Translation language" is set to English. I've tried with different languages, and I'm getting the same problem. This is an example video: https://www.youtube.com/watch?v=lZMMqMvY1d0
My OS is Linux Mint 20.2 (but I guess it shouldn't make a difference)
This is a screenshot: 
![image](https://user-images.githubusercontent.com/35060206/126163769-a4693354-c860-4236-9545-043784be5b7e.png)

**Comment by Nitrino** [comment]
@Sentero-esp12 I was able to repeat this issue in Firefox, it seems Google blocks requests from Firefox.
I need some time to investigate the issue. 
While please use the version for Google Chrome. I will inform in this thread as soon as I will fix the issue

**Comment by jtraub** [comment]
@Nitrino I do believe that [this change](https://blog.mozilla.org/security/2021/07/12/firefox-90-supports-fetch-metadata-request-headers/) is the reason why Google Translate responds with 403 error on any requests from background script

**Comment by Nitrino** [comment]
Hi @jtraub 
Thanks for investigating, it will save me a lot of time 👍

**Comment by Nitrino** [comment]
Hi @Sentero-esp12, @jtraub 
It seems I was able to come up with a hack to fix the work in Firefox. 

Can you please test this version?
[release.zip](https://github.com/Nitrino/easysubs/files/6985396/release.zip)

**Comment by jtraub** [comment]
@Nitrino works for me in Fx 91.0 (64-bit) under Linux

**Comment by Nitrino** [comment]
@jtraub Cool, I will release soon

**Comment by Nitrino** [comment]
Version 1.5.6 released
