### ISSUE TITLE
Buttons do not show after Netflix updated the UI

### ISSUE THREAD

**Issue by Essam3152** [Nitrino/easysubs#208]
Hi, Netflix updated the UI today, and the buttons of the extension disappeared.

![222](https://user-images.githubusercontent.com/87686356/132493279-aab4b0ed-d520-4f5f-abee-b43d1677ed21.png)

**Comment by Nitrino** [comment]
@Essam3152 Thanks for feedback. I will check and fix soon

**Comment by Essam3152** [comment]
@Nitrino Thank you.

**Comment by djpecot** [comment]
I've started peeking into it a little already. Looks like the CSS selectors have changed, namely:

- `playerContainerSelector()` should be `'.ltr-fntwn3'` (I think)
- `settingsSelector()` looks like `'[aria-label="Full screen"]'`

**Comment by Essam3152** [comment]
@Nitrino This might help you.

https://github.com/rsimmons/subadub/commit/7b1af4c0a4ae4f660c5ae99b05e43062846ce68d

https://github.com/Tithen-Firion/UserScripts/commit/5b6c2c2e088a08d82bc56f4bcc66a9363abf3b5f

**Comment by Nitrino** [comment]
Netflix support fixed. Soon to be released
