### ISSUE TITLE
extension not working on safari 

### ISSUE THREAD

**Issue by cmkw** [Nitrino/easysubs#210]
Hey I'm using the extension from App Store, finding it not works well on YouTube. There's no translation at all When the mouse hovering over the word or clicking it. It does not work on Netflix too, I cannot even see the easysub button on Netflix (sure about the extension was turned on). Meantime I am using adguard, if there's any connections.

**environment**
Big Sur Version 11.5.2
safari Version 14.1.2 

**snipshots**
![Snipaste_2021-09-19_14-01-07](https://user-images.githubusercontent.com/56218097/133917229-d5b10406-1388-4dbf-9f1c-1b3a8b04f914.jpg)
![Snipaste_2021-09-19_14-00-18](https://user-images.githubusercontent.com/56218097/133917233-d9c8afbc-b229-434a-953a-bf0ea1ac931e.jpg)
s

**Comment by Nitrino** [comment]
Hi @cmkw. 
Unfortunately, I have to remove the extension from the app store.
In Safari, for some reason unknown to me, the necessary functions stopped working and at the moment I have not found a solution.
For now, it's best to use Chrome or Firefox.
