### ISSUE TITLE
Easysubs(Firefox) stopped working on kino.pub

### ISSUE THREAD

**Issue by Sserebryan** [Nitrino/easysubs#213]
Easysubs(Firefox) stopped working on kino.pub, Subtitles disappear when the extension is turned on. See GIF below.

![CleanShot 2022-05-08 at 20 43 23](https://user-images.githubusercontent.com/9846671/167306610-1f1860ca-cbec-433c-9b29-556cf5d66b46.gif)

OS: MacOS Monterey(M1)
Firefox: 100.0 (64-bit) 
Easysubs version:  1.5.5

**Comment by DvoeglazovIlya** [comment]
Maybe it help:
