### ISSUE TITLE
breaks Jira

### ISSUE THREAD

**Issue by gkavboy** [Nitrino/easysubs#218]
This extension breaks the Jira site.
On click site buttons I see allert message:
![Screenshot_20220808_171620](https://user-images.githubusercontent.com/25064847/183440505-9eb2d8e3-bd0d-4df6-9c2b-90c5723d3e1f.png)
After reload page show normaly, but on other click all repeat.

**Comment by Nitrino** [comment]
Hi @gkavboy Are you sure the error is related to the extension?
We don't have a code related to this.

**Comment by Nitrino** [comment]
Closed due to no response
