### ISSUE TITLE
There is a site with movies for English language learners need to embed a plugin in allvideo.monster

### ISSUE THREAD

**Issue by RomanPron** [Nitrino/easysubs#225]
There is a site https://moviessub.club/ with movies with double subtitles for English language learners need to embed a plugin in allvideo.monster (based on which).
Cooperation options, paid access with monthly payment for customers

**Comment by Nitrino** [comment]
Hi @RomanPron 
Sorry for the long reply. 
I'm not quite sure what my extension is for on this service, as it already outputs a double translation
