### ISSUE TITLE
Is Netflix still supported ? 

### ISSUE THREAD

**Issue by NikitaPomies** [Nitrino/easysubs#227]
Hello
 thanks for developing the app.

I don't see where Netflix and english with fun are supported in the current src code of master. Is their any reason you removed 
these services ?

**Comment by Nitrino** [comment]
@NikitaPomies Hey. 
Yes, Netflix and english with fun are still supported. The current master brunch has a new version of the extension that is not yet finished. Or rather, it's no longer relevant. The actual fully rewritten version is now in the v3.0 branch https://github.com/Nitrino/easysubs/tree/v3.0
It doesn't have Netflix and english with fun yet either, but I plan to add them today or tomorrow.

Some questions:
1. Do you use english with fun? I was thinking about whether or not I needed to support it
2. Do you have a plan to add features? Then I can rather merge version v3.0 into the master branch

**Comment by Nitrino** [comment]
v3.0 merged into master brunch with Netflix support.
Support for english with fun remains in question.

**Comment by NikitaPomies** [comment]
Hello 

Thanks for the update I will use this new version. 

I do not have any enhancement in mind right now but If I have any idea, I would be happy to contribute !

**Comment by NikitaPomies** [comment]
An I forgot : No I do not use English with fun.

**Comment by Nitrino** [comment]
@NikitaPomies If there are bugs in the new version, feel free to write me about them. This is not a release yet and I haven't had time to test

**Comment by Nitrino** [comment]
v3.0.0 has been released
