### ISSUE TITLE
Can subtitles support bilingual letters?

### ISSUE THREAD

**Issue by zuanbishuihun** [Nitrino/easysubs#228]
Hello developer, I would like to ask if this plugin can provide continuous bilingual subtitles, that is, **the original text and translated text will always appear**, or I have not found this function, thank you!

**Comment by Nitrino** [comment]
@zuanbishuihun Hi. 
Unfortunately this is not supported right now. 
We can't add automatic translation of all text, as we will run into google translate limits. 
We can only add output of two subtitles available on the service, but I don't know how useful it is

**Comment by zuanbishuihun** [comment]
All right, thank you for your development. ：)
