### ISSUE TITLE
Is the version in Master working?

### ISSUE THREAD

**Issue by StevenMaMei** [Nitrino/easysubs#233]
I built the code from master because I want to start experimenting with this project. I built the project and loaded the dist/ folder in Chrome. However, when using Youtube, it seems that the extension is not working... 
I have developer mode enabled.
Am I missing something?

**Comment by Nitrino** [comment]
@StevenMaMei Hi, sorry for long reply.
The master now has a completely new version, which will soon have a release.
YouTube works in this version.
Not sure if the build command is working, try using `npm dev`

**Comment by StevenMaMei** [comment]
I used npm dev and it worked. Thanks!
