### ISSUE TITLE
Не работают  субтитры на нетфликс

### ISSUE THREAD

**Issue by downntwinkle** [Nitrino/easysubs#242]
Добрый день! Если я  включаю Easysubs при просмотре нетфликс, у меня пропадают все субтитры. При просмотре ютюб такой проблемы нет.  Подскажите,  пожалуйста,  что можно сделать с данной проблемой? 

https://github.com/user-attachments/assets/9d9e0561-202c-4bb4-bdd1-1208cf080fd1

**Comment by Nitrino** [comment]
@downntwinkle Добрый день. 
На днях будет релиз новой большой версии в которой это исправлено.
Пока можешь установить бета версию
[v3.0.0-rc15.zip](https://github.com/user-attachments/files/16375536/v3.0.0-rc15.zip)

**Comment by Nitrino** [comment]
@downntwinkle Новый релиз уже в сторе
https://chromewebstore.google.com/detail/easysubs-%E2%80%93-learn-language/ocelmccppkcibiflhhepafdjjomimddf?hl=en
