### ISSUE TITLE
Проблема в работе AUTO PAUSE 

### ISSUE THREAD

**Issue by downntwinkle** [Nitrino/easysubs#243]
После обновления при просмотре и ютюб,  и нетфликс   при включенной функции AUTO PAUSE видео встает на паузу как-то неконтролируемо. Видео работает,  далее при наведении на субтитр оно останавливается,  но если убрать мышку с субтитра, видео не запускается. Также видео может останавливаться просто  так, то есть даже если не наводить на субтитр
Если отключить AUTO PAUSE  проблема решается.  Функция была очень полезна,  без нее жить стало тяжелее) 
https://github.com/user-attachments/assets/c37feec2-3bdd-4ca2-a250-ef918380d490

**Comment by Nitrino** [comment]
@downntwinkle Привет. Действительно странное поведении. Можешь скинуть скрины своих настроек на основной вкладке и на вкладке experimental?

**Comment by downntwinkle** [comment]
@Nitrino 
![image](https://github.com/user-attachments/assets/1a89ebe5-e86d-4f1e-b6f2-6d304dc834ac)
![image](https://github.com/user-attachments/assets/e7277870-20ce-442d-bb90-1f328098a653)

**Comment by Nitrino** [comment]
@downntwinkle Кажется у тебя включена автопауза после каждого саба и отключена пауза при наведении курсора. 
Сделай ровно на оборот:
auto pause - выключен
auto stop - включен

В следующей версии переименую настройки и добавлю описание что бы было понятнее

**Comment by downntwinkle** [comment]
@Nitrino  спасибо,  помогло!
